# Use powerline
USE_POWERLINE="true"
# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
  source /usr/share/zsh/manjaro-zsh-prompt
fi

# Alias
alias icat="kitty +kitten icat"
alias dotdrop="/home/juan/dotfiles/dotdrop.sh"

## Starship prompt
## ~/.zshrc
eval "$(starship init zsh)"

## History settings
HISTFILE=~/.zhistory
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory

## Path settings
export PATH=/home/juan/.local/bin:$PATH
