# AUTOCOMPLETION

# initialize autocompletion
# autoload -U compinit
autoload -U predict-on

# history setup
setopt APPEND_HISTORY
setopt SHARE_HISTORY
HISTFILE=$HOME/.zhistory
SAVEHIST=1000
HISTSIZE=999
setopt HIST_EXPIRE_DUPS_FIRST
setopt EXTENDED_HISTORY

# autocompletion using arrow keys (based on history)
#bindkey '\e[A' history-search-backward
#bindkey '\e[B' history-search-forward

# autocompletion using arrow keys (based on history of same command)
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# GENERAL

# (bonus: Disable sound errors in Zsh)

# never beep
setopt NO_BEEP

# Use powerline
USE_POWERLINE="true"

# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
  source /usr/share/zsh/manjaro-zsh-prompt
fi

# Alias
alias icat="kitty +kitten icat"
alias dotdrop="/home/juan/dotfiles/dotdrop.sh"

## Starship prompt
## ~/.zshrc
#eval "$(starship init zsh)"

## Path settings
export PATH=/home/juan/.local/bin:$PATH
