cursor #ffffff
cursor_text_color #ffffff

foreground            #ffffff
background            #222226
selection_foreground  #ffffff
selection_background  #bbd1e5
url_color             #6f8396

color0   #1d1d20
color1   #c96784
color2   #4b9654
color3   #bbb554
color4   #73899f
color5   #243545
color6   #6f8396
color7   #94989d
color8   #7a7d82
color9   #ca7e95
color10  #75b47d
color11  #e1dc92
color12  #8093a5
color13  #9fb1c3
color14  #b9c6d2
color15  #d4d6d9
